default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  login: zhela
  password: 10side
  database: poems

production:
  <<: *default
  host: ec2-107-22-170-249.compute-1.amazonaws.com
  port: 5432
  database: dejm35d897epel
  login: xstnhgqlhsrivg
  password: GmLO36uPeQdZOZDst63Zy4SZOo
