# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f57fb28330e20f635ed8366e54df4e9521629bd284a8d58de1f47d6a0ed22bbeaabb8a3b7366d4830c97f93b93dd7d0378b37ed5aa7878a05f7cd3a2696da4c

test:
  secret_key_base: ff0e2d6026ce7658998eec362d705d6c948d87d4cb798bddab127503ac11828a14d28166a2fae4a32cb36547af7fcc8f0f186d8e4ae7761cf4972786915c0d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
